spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: payment-module
          uri: http://localhost:8088
          predicates:
            - Path=/payment/**
          filters:
            - RewritePath=/payment/(?<segment>.*), /${segment}
        - id: product-module
          uri: http://localhost:8087
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/(?<segment>.*), /${segment}
        - id: inventory-module
          uri: http://localhost:8089
          predicates:
            - Path=/inventory/**
          filters:
            - RewritePath=/inventory/(?<segment>.*), /${segment}

server:
  port: 8086

logging:
  level:
    root: DEBUG
    com.example.payment: DEBUG
    com.example.product: DEBUG
    com.example.inventory: DEBUG
